version: '3.8'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8100:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
      WORDPRESS_DEBUG: ${WP_DEBUG:-true}
      WORDPRESS_TABLE_PREFIX: ${DB_TABLE_PREFIX:-wp_}
      CACHE_LOC: ${CACHE_LOC:-/var/www/html/wp-content/cache}
      TTL: ${TTL:-80000}
      PURGE_PATH: ${PURGE_PATH:-/__cache/purge}
      PURGE_KEY: ${PURGE_KEY:-}
      BYPASS_HOME: ${BYPASS_HOME:-false}
      BYPASS_PATH_PREFIXES: ${BYPASS_PATH_PREFIXES:-/wp-admin,/wp-content,/wp-includes,/wp-json,/feed}
      CACHE_RESPONSE_CODES: ${CACHE_RESPONSE_CODES:-200,404,405}
      CADDY_GLOBAL_OPTIONS: |
        email lfelipeapo@gmail.com
        auto_https disable_redirects
        debug
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL', 'https://dev.local');
        define('WP_HOME', 'https://dev.local');
    volumes:
      - ./data/wp-content:/var/www/html/wp-content
      - ./data/wp-content/themes/thabatta-adv-theme:/var/www/html/wp-content/themes/thabatta-adv-theme
      - ./data/sqlite:/var/www/html/wp-content/database 
      - caddy_data:/data
      - caddy_config:/config
    tty: true

volumes:
  caddy_data:
  caddy_config:
