version: '3.9'

services:
  wordpress:
    image: wpeverywhere/frankenwp:latest-php8.3
    restart: always
    ports:
      - "8000:80"  # HTTP principal
      - "8100:443" # HTTPS principal
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER:-exampleuser}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-examplepass}
      WORDPRESS_DB_NAME: ${DB_NAME:-exampledb}
      WORDPRESS_DEBUG: ${WP_DEBUG:-"true"}
      WORDPRESS_TABLE_PREFIX: ${DB_TABLE_PREFIX:-wp_}
      CACHE_LOC: /var/www/html/wp-content/cache
      TTL: 80000
      PURGE_PATH: /__cache/purge
      PURGE_KEY: ""
      BYPASS_HOME: "false" # Alterado para string
      BYPASS_PATH_PREFIXES: "/wp-admin,/wp-content,/wp-includes,/wp-json,/feed"
      CACHE_RESPONSE_CODES: "000"
      CADDY_GLOBAL_OPTIONS: |
        email lfelipeapo@gmail.com
        auto_https disable_redirects
        debug
      WORDPRESS_CONFIG_EXTRA: |
        if (!defined('WP_HOME')) {
            define('WP_HOME', getenv('WP_HOME') ?: 'https://localhost:8100');
        }
        if (!defined('WP_SITEURL')) {
            define('WP_SITEURL', getenv('WP_SITEURL') ?: 'https://localhost:8100');
        }
        if (!defined('FS_METHOD')) {
            define('FS_METHOD', 'direct');
        }
    volumes:
    - ./data/wp-content:/var/www/html/wp-content
    - ./data:/var/www/html
    - ./debug/dev.ini:/usr/local/etc/php/conf.d/dev.ini
    depends_on:
      - db
    tty: true

  db:
    image: mariadb:latest
    restart: always
    ports:
      - "3311:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME:-exampledb}
      MYSQL_USER: ${DB_USER:-exampleuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-examplepass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-examplepass}
    volumes:
      - dbwp:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8086:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-examplepass}
    depends_on:
      - db

  sftp:
    image: atmoz/sftp
    restart: always
    ports:
      - "2222:22" # Porta SFTP
    volumes:
      - ./data:/home/wp-user/data
    environment:
      SFTP_USERS: "wp-user:password:1001" # Usuário e senha para acesso SFTP

volumes:
  dbwp:
